In [1]:
#dataset is at ../liar_dataset/liar.csv
DATASET_PATH = '../liar_dataset/liar prepped.csv'
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [51]:
dataset = pd.read_csv(DATASET_PATH, index_col=['id'])
dataset

       label                                  prepped statement
id
0          0  building wall u mexico border take literally y...
1          1          wisconsin pace double number layoffs year
2          1                 john mccain done nothing help vets
3          0  suzanne bonamici supports plan cut choice medi...
4          1  asked reporter whether hes center criminal sch...
...      ...                                                ...
12804      0  first time decade imports accounted less half ...
12805      0  donald trump bankrupted companies twice four t...
12806      0  john mccain george bush absolutely plan univer...
12807      1  new poll shows 62 percent support president pl...
12808      1  one claims report vindicating new jersey gov c...

[12809 rows x 2 columns]

In [52]:
dataset['label'].value_counts()

label
0    7155
1    5654
Name: count, dtype: int64

In [53]:
corpus = dataset['prepped statement'].values
corpus

array(['building wall u mexico border take literally years',
       'wisconsin pace double number layoffs year',
       'john mccain done nothing help vets', ...,
       'john mccain george bush absolutely plan universal health care',
       'new poll shows 62 percent support president plan reform health care means letting choose keeping private insurance public health insurance plan',
       'one claims report vindicating new jersey gov chris christie bridge scandal conclusive'],
      dtype=object)

In [54]:
len(corpus)

12809

In [57]:
#apply vectorizer: Bag of Words, and create a dataframe from the matrix
vectorizer = CountVectorizer()
matrix = vectorizer.fit_transform(corpus)
words = vectorizer.get_feature_names_out()
dfBow = pd.DataFrame(matrix.todense(), columns=words)
dfBow

,00,000,000new,014,02,024,029,033,036,04,...,zippo,zombie,zombies,zone,zones,zoning,zoo,zuckerberg,zuckerbergs,ʺmore
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12804,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12805,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12806,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12807,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12808,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
#get only the columns with words
wordColumns = [word for word in dfBow.columns if word.isalpha() and len(word) >= 3]
len(wordColumns)

12554

In [71]:
dfBow[wordColumns]

,aaa,aaron,aarp,aba,abandoned,abandoning,abbas,abbott,abc,abdul,...,zippo,zombie,zombies,zone,zones,zoning,zoo,zuckerberg,zuckerbergs,ʺmore
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12804,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12805,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12806,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12807,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12808,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
result = pd.concat([dataset, dfBow[wordColumns]], axis=1)
result.drop(columns=['prepped statement'], inplace=True)
result

,label,aaa,aaron,aarp,aba,abandoned,abandoning,abbas,abbott,abc,...,zippo,zombie,zombies,zone,zones,zoning,zoo,zuckerberg,zuckerbergs,ʺmore
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12804,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12805,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12806,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12807,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12808,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
result.to_csv('../liar_dataset/liar BoW.csv', index_label='id')

In [2]:
dfBow = pd.read_csv('../liar_dataset/liar BoW.csv', index_col='id')
dfBow

,label,aaa,aaron,aarp,aba,abandoned,abandoning,abbas,abbott,abc,...,zippo,zombie,zombies,zone,zones,zoning,zoo,zuckerberg,zuckerbergs,ʺmore
id,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12804,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12805,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12806,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12807,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12808,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
wordCols = dfBow.columns.values[1:]
wordCols

array(['aaa', 'aaron', 'aarp', ..., 'zuckerberg', 'zuckerbergs', 'ʺmore'],
      dtype=object)

In [20]:
wordFrequency = dfBow[wordCols].sum(axis=0)
print(wordFrequency)

aaa            4
aaron          2
aarp           4
aba            1
abandoned      2
              ..
zoning         2
zoo            1
zuckerberg     1
zuckerbergs    1
ʺmore          1
Length: 12554, dtype: int64

In [21]:
wordFrequency.mean()

10.44909988848176

In [22]:
wordFrequency.index

Index(['aaa', 'aaron', 'aarp', 'aba', 'abandoned', 'abandoning', 'abbas',
       'abbott', 'abc', 'abdul',
       ...
       'zippo', 'zombie', 'zombies', 'zone', 'zones', 'zoning', 'zoo',
       'zuckerberg', 'zuckerbergs', 'ʺmore'],
      dtype='object', length=12554)

In [26]:
wordFrequency.at['aaa']

4

In [40]:
#from nltk.corpus import words
import nltk
nltk.download('words')

[nltk_data] Downloading package words to C:\Users\Ștefan
[nltk_data]     Vlădescu\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!

True

In [41]:
#columns to be dropped: rare words, of frequency 1
#words that are not in the english dictionary
from nltk.corpus import words
#realWords = [word for word in wordFrequency.index if word in words.words()]
#print(len(realWords))
#rareWords = [word for word in wordFrequency.index if wordFrequency.at[word] <= 1]
#print(len(dropCols))

KeyboardInterrupt: